name: pManager
description: A package to handle media uploads.
version: 0.0.1
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  photo_manager: ^3.2.3
  firebase_auth: 5.3.0
  shared_preferences: 2.2.2
